import { AUTH_SERVICE_URI } from "#root/utils/constants";
import { log } from "#root/utils/logger";
import axios from "axios";

export const REPORT_PROCEDURES = {
  GetEmployeeLoginReportForClient: "GetEmployeeLoginReportForClient",
  GetEmployeeLoginReportByTeam: "GetEmployeeLoginReportByTeam",
  GetEmployeeFullActivity: "GetEmployeeFullActivity",
  GetEmployeeStatusChange: "GetEmployeeStatusChange",
  GetEmployeeTasksSummary: "GetEmployeeTasksSummary",
};

export const DEFAULT_REPORTS = [
  {
    reportId: "1",
    reportName: "Employee Login Report",
    procedureName: REPORT_PROCEDURES.GetEmployeeLoginReportForClient,
    searchFields: [
      {
        fieldName: "clientId",
        fieldType: "form-text",
        label: "Client ID",
        defaultValue: "",
        options: [],
        mandatory: true,
        visible: false,
        hidden: true,
      },
      {
        fieldName: "userId",
        fieldType: "form-select",
        defaultValue: "",
        label: "Employee",
        options: [],
        mandatory: false,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "startDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Start Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "endDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "End Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
    ],
    reportFields: [
      {
        fieldName: "name",
        fieldType: "text",
        label: "Name",
        visible: true,
      },
      {
        fieldName: "action",
        fieldType: "text",
        label: "Action",
        visible: true,
      },
      {
        fieldName: "timestamp",
        fieldType: "date-time",
        label: "Timestamp",
        visible: true,
      },
    ],
  },
  {
    reportId: "2",
    reportName: "Team Login Report",
    procedureName: REPORT_PROCEDURES.GetEmployeeLoginReportByTeam,
    searchFields: [
      {
        fieldName: "clientId",
        fieldType: "form-text",
        label: "Client ID",
        defaultValue: "",
        options: [],
        mandatory: true,
        visible: false,
        hidden: true,
      },
      {
        fieldName: "teamId",
        fieldType: "form-select",
        defaultValue: "",
        label: "Team Name",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "startDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Start Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "endDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "End Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
    ],
    reportFields: [
      {
        fieldName: "name",
        fieldType: "text",
        label: "Employee Name",
        visible: true,
      },
      {
        fieldName: "action",
        fieldType: "text",
        label: "Action",
        visible: true,
      },
      {
        fieldName: "timestamp",
        fieldType: "date-time",
        label: "Timestamp",
        visible: true,
      },
    ],
  },
  {
    reportId: "3",
    reportName: "Employee Activity Report",
    procedureName: REPORT_PROCEDURES.GetEmployeeFullActivity,
    searchFields: [
      {
        fieldName: "clientId",
        fieldType: "form-text",
        label: "Client ID",
        defaultValue: "",
        options: [],
        mandatory: true,
        visible: false,
        hidden: true,
      },
      {
        fieldName: "userId",
        fieldType: "form-select",
        defaultValue: "",
        label: "Employee",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "startDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Start Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "endDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "End Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
    ],
    reportFields: [
      {
        fieldName: "name",
        fieldType: "text",
        label: "Employee Name",
        visible: true,
      },
      {
        fieldName: "timestamp",
        fieldType: "date-time",
        label: "Timestamp",
        visible: true,
      },
      {
        fieldName: "action",
        fieldType: "text",
        label: "Action",
        visible: true,
      },
      {
        fieldName: "description",
        fieldType: "text",
        label: "Action Description",
        visible: true,
      },
    ],
  },
  {
    reportId: "4",
    reportName: "Employee Status Change Report",
    procedureName: REPORT_PROCEDURES.GetEmployeeStatusChange,
    searchFields: [
      {
        fieldName: "clientId",
        fieldType: "form-text",
        label: "Client ID",
        defaultValue: "",
        options: [],
        mandatory: true,
        visible: false,
        hidden: true,
      },
      {
        fieldName: "userId",
        fieldType: "form-select",
        defaultValue: "",
        label: "Employee",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "currentDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "startDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Start Date",
        options: [],
        mandatory: false,
        visible: false,
        hidden: false,
      },
      {
        fieldName: "endDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "End Date",
        options: [],
        mandatory: false,
        visible: false,
        hidden: false,
      },
    ],
    reportFields: [
      {
        fieldName: "name",
        fieldType: "text",
        label: "Employee Name",
        visible: true,
      },
      {
        fieldName: "action",
        fieldType: "text",
        label: "Action",
        visible: false,
      },
      {
        fieldName: "timestamp",
        fieldType: "date-time",
        label: "Timestamp",
        visible: true,
      },
      {
        fieldName: "fromStatus",
        fieldType: "text",
        label: "From Status",
        visible: true,
      },
      {
        fieldName: "toStatus",
        fieldType: "text",
        label: "To Status",
        visible: true,
      },
    ],
  },
  {
    reportId: "5",
    reportName: "Employee Task Summary Report",
    procedureName: REPORT_PROCEDURES.GetEmployeeTasksSummary,
    searchFields: [
      {
        fieldName: "clientId",
        fieldType: "form-text",
        label: "Client ID",
        defaultValue: "",
        options: [],
        mandatory: true,
        visible: false,
        hidden: true,
      },
      {
        fieldName: "userId",
        fieldType: "form-select",
        defaultValue: "",
        label: "Employee",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "startDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "Start Due Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
      {
        fieldName: "endDate",
        fieldType: "form-date",
        defaultValue: "",
        label: "End Due Date",
        options: [],
        mandatory: true,
        visible: true,
        hidden: false,
      },
    ],
    reportFields: [
      {
        fieldName: "name",
        fieldType: "text",
        label: "Employee Name",
        visible: true,
      },
      {
        fieldName: "taskName",
        fieldType: "text",
        label: "Task Name",
        visible: true,
      },
      {
        fieldName: "isCompleted",
        fieldType: "text",
        label: "Is Completed?",
        visible: true,
      },
      {
        fieldName: "dueDate",
        fieldType: "date-time",
        label: "Due Date",
        visible: true,
      },
      {
        fieldName: "completedDate",
        fieldType: "date-time",
        label: "Completed Date",
        visible: true,
      },
    ],
  },
];
