version: "3"
services:
  api-gateway:
    container_name: api-gateway
    build:
      target: production
    command: yarn start

  auth-service:
    container_name: auth-service
    build:
      target: production
    command: yarn start

  application-data-service:
    build:
      target: production
    command: yarn start
