version: "3"
services:
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@a.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - auth-service-db
      - tasks-service-db
    volumes:
      - ./pgdata/pgadmin:/var/lib/pgadmin
